// Generated by purs version 0.13.8
"use strict";
var $foreign = require("./foreign.js");
var Data_Unit = require("../Data.Unit/index.js");
var makeStateless = function (component) {
    return function (render) {
        return $foreign.make()(component)({
            initialState: Data_Unit.unit,
            render: function (self) {
                return render(self.props);
            }
        });
    };
};
module.exports = {
    makeStateless: makeStateless,
    createComponent: $foreign.createComponent,
    make: $foreign.make
};
