// Generated by purs version 0.13.8
"use strict";
var $foreign = require("./foreign.js");
var React_Basic = require("../React.Basic/index.js");
var unsafeCreateDOMComponent = $foreign.unsafeCreateDOMComponent_(React_Basic.element);
module.exports = {
    unsafeCreateDOMComponent: unsafeCreateDOMComponent,
    unsafeCreateDOMComponent_: $foreign.unsafeCreateDOMComponent_
};
