// Generated by purs version 0.13.8
"use strict";
var Components_Toggle = require("../Components.Toggle/index.js");
var Data_Unit = require("../Data.Unit/index.js");
var React_Basic_Classic = require("../React.Basic.Classic/index.js");
var React_Basic_DOM = require("../React.Basic.DOM/index.js");
var React_Basic_DOM_Generated = require("../React.Basic.DOM.Generated/index.js");
var component = React_Basic_Classic.createComponent("App");
var app = React_Basic_Classic.makeStateless(component)(function (v) {
    return React_Basic_DOM_Generated.div_([ React_Basic_DOM_Generated.h1_([ React_Basic_DOM.text("Hello world") ]), React_Basic_DOM_Generated.h2_([ React_Basic_DOM.text("YOLO") ]), Components_Toggle.toggle({
        initialValue: true
    }), Components_Toggle.toggle({
        initialValue: false
    }) ]);
})(Data_Unit.unit);
module.exports = {
    component: component,
    app: app
};
