// Generated by purs version 0.13.8
"use strict";
var $foreign = require("./foreign.js");
var Data_Functor = require("../Data.Functor/index.js");
var Data_Nullable = require("../Data.Nullable/index.js");
var Effect = require("../Effect/index.js");
var getElementById = function (eid) {
    var $14 = Data_Functor.map(Effect.functorEffect)(Data_Nullable.toMaybe);
    var $15 = $foreign["_getElementById"](eid);
    return function ($16) {
        return $14($15($16));
    };
};
module.exports = {
    getElementById: getElementById
};
