// Generated by purs version 0.13.8
"use strict";
var $foreign = require("./foreign.js");
var $$throw = function ($8) {
    return $foreign.throwException($foreign.error($8));
};
module.exports = {
    "throw": $$throw,
    error: $foreign.error,
    throwException: $foreign.throwException
};
