// Generated by purs version 0.13.8
"use strict";
var Functor = function (map) {
    this.map = map;
};
var map = function (dict) {
    return dict.map;
};
module.exports = {
    Functor: Functor,
    map: map
};
