// Generated by purs version 0.13.8
"use strict";
var Apply = function (Functor0, apply) {
    this.Functor0 = Functor0;
    this.apply = apply;
};
var apply = function (dict) {
    return dict.apply;
};
module.exports = {
    Apply: Apply,
    apply: apply
};
