// Generated by purs version 0.13.8
"use strict";
var $foreign = require("./foreign.js");
var HeytingAlgebra = function (conj, disj, ff, implies, not, tt) {
    this.conj = conj;
    this.disj = disj;
    this.ff = ff;
    this.implies = implies;
    this.not = not;
    this.tt = tt;
};
var not = function (dict) {
    return dict.not;
};
var disj = function (dict) {
    return dict.disj;
};
var heytingAlgebraBoolean = new HeytingAlgebra($foreign.boolConj, $foreign.boolDisj, false, function (a) {
    return function (b) {
        return disj(heytingAlgebraBoolean)(not(heytingAlgebraBoolean)(a))(b);
    };
}, $foreign.boolNot, true);
module.exports = {
    HeytingAlgebra: HeytingAlgebra,
    disj: disj,
    not: not,
    heytingAlgebraBoolean: heytingAlgebraBoolean
};
