// Generated by purs version 0.13.8
"use strict";
var Unsafe_Coerce = require("../Unsafe.Coerce/index.js");
var toNonElementParentNode = Unsafe_Coerce.unsafeCoerce;
module.exports = {
    toNonElementParentNode: toNonElementParentNode
};
