// Generated by purs version 0.13.8
"use strict";
var Data_HeytingAlgebra = require("../Data.HeytingAlgebra/index.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var React_Basic_Classic = require("../React.Basic.Classic/index.js");
var React_Basic_DOM = require("../React.Basic.DOM/index.js");
var React_Basic_DOM_Events = require("../React.Basic.DOM.Events/index.js");
var React_Basic_DOM_Generated = require("../React.Basic.DOM.Generated/index.js");
var component = React_Basic_Classic.createComponent("App");
var toggle = (function () {
    var render = function (self) {
        var on = Data_Maybe.fromMaybe(self.props.initialValue)(self.state);
        return React_Basic_DOM_Generated.button()({
            onClick: React_Basic_DOM_Events.capture_(self.setState((function () {
                var $1 = Data_HeytingAlgebra.not(Data_HeytingAlgebra.heytingAlgebraBoolean);
                var $2 = Data_Maybe.fromMaybe(on);
                return function ($3) {
                    return Data_Maybe.Just.create($1($2($3)));
                };
            })())),
            children: [ React_Basic_DOM.text((function () {
                if (on) {
                    return "On!!!!";
                };
                return "Off";
            })()) ]
        });
    };
    return React_Basic_Classic.make()(component)({
        initialState: Data_Maybe.Nothing.value,
        render: render
    });
})();
module.exports = {
    component: component,
    toggle: toggle
};
